// Layer data copied from Miryoku QMK (miryoku_babel/miryoku_layer_alternatives.h):
// https://github.com/manna-harbour/miryoku_qmk/blob/miryoku/users/manna-harbour_miryoku/miryoku_babel/miryoku_layer_alternatives.h
// Each layer is 36 QMK keycode tokens: rows 1-3 (left 5, right 5) then thumbs (left 3, right 3).
// Upstream keeps 4 unused (U_NP) positions in the thumb row; they are dropped here.

export type Tokens = readonly string[];

export const LAYERS: Record<string, Tokens> = {
  "BASE_AZERTY_FLIP": [
    "KC_A", "KC_Z", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_Q)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_M)",
    "LT(U_BUTTON,KC_W)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_COMM", "KC_DOT", "ALGR_T(KC_SLSH)", "LT(U_BUTTON,KC_QUOT)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_BEAKL15_FLIP": [
    "KC_Q", "KC_H", "KC_O", "KC_U", "KC_X", "KC_G", "KC_C", "KC_R", "KC_F", "KC_Z",
    "LGUI_T(KC_Y)", "LALT_T(KC_I)", "LCTL_T(KC_E)", "LSFT_T(KC_A)", "KC_DOT", "KC_D", "LSFT_T(KC_S)", "LCTL_T(KC_T)", "LALT_T(KC_N)", "LGUI_T(KC_B)",
    "LT(U_BUTTON,KC_J)", "ALGR_T(KC_SLSH)", "KC_COMM", "KC_K", "KC_QUOT", "KC_W", "KC_M", "KC_L", "ALGR_T(KC_P)", "LT(U_BUTTON,KC_V)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_COLEMAK_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_G", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_D", "KC_H", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_K", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_COLEMAKDH_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_G", "KC_M", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_D", "KC_V", "KC_K", "KC_H", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_COLEMAKDHK_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_G", "KC_K", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_D", "KC_V", "KC_M", "KC_H", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_DVORAK_FLIP": [
    "KC_QUOT", "KC_COMM", "KC_DOT", "KC_P", "KC_Y", "KC_F", "KC_G", "KC_C", "KC_R", "KC_L",
    "LGUI_T(KC_A)", "LALT_T(KC_O)", "LCTL_T(KC_E)", "LSFT_T(KC_U)", "KC_I", "KC_D", "LSFT_T(KC_H)", "LCTL_T(KC_T)", "LALT_T(KC_N)", "LGUI_T(KC_S)",
    "LT(U_BUTTON,KC_SLSH)", "ALGR_T(KC_Q)", "KC_J", "KC_K", "KC_X", "KC_B", "KC_M", "KC_W", "ALGR_T(KC_V)", "LT(U_BUTTON,KC_Z)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_HALMAK_FLIP": [
    "KC_W", "KC_L", "KC_R", "KC_B", "KC_Z", "KC_QUOT", "KC_Q", "KC_U", "KC_D", "KC_J",
    "LGUI_T(KC_S)", "LALT_T(KC_H)", "LCTL_T(KC_N)", "LSFT_T(KC_T)", "KC_COMM", "KC_DOT", "LSFT_T(KC_A)", "LCTL_T(KC_E)", "LALT_T(KC_O)", "LGUI_T(KC_I)",
    "LT(U_BUTTON,KC_F)", "ALGR_T(KC_M)", "KC_V", "KC_C", "KC_SLSH", "KC_G", "KC_P", "KC_X", "ALGR_T(KC_K)", "LT(U_BUTTON,KC_Y)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_WORKMAN_FLIP": [
    "KC_Q", "KC_D", "KC_R", "KC_W", "KC_B", "KC_J", "KC_F", "KC_U", "KC_P", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_H)", "LSFT_T(KC_T)", "KC_G", "KC_Y", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_O)", "LGUI_T(KC_I)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_M", "KC_C", "KC_V", "KC_K", "KC_L", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_QWERTY_FLIP": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_QUOT)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_QWERTZ_FLIP": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Z", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_QUOT)",
    "LT(U_BUTTON,KC_Y)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_FUN,KC_DEL)", "LT(U_NUM,KC_BSPC)", "LT(U_SYM,KC_ENT)", "LT(U_MOUSE,KC_TAB)", "LT(U_NAV,KC_SPC)", "LT(U_MEDIA,KC_ESC)",
  ],
  "BASE_AZERTY": [
    "KC_A", "KC_Z", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_Q)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_M)",
    "LT(U_BUTTON,KC_W)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_COMM", "KC_DOT", "ALGR_T(KC_SLSH)", "LT(U_BUTTON,KC_QUOT)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_BEAKL15": [
    "KC_Q", "KC_H", "KC_O", "KC_U", "KC_X", "KC_G", "KC_C", "KC_R", "KC_F", "KC_Z",
    "LGUI_T(KC_Y)", "LALT_T(KC_I)", "LCTL_T(KC_E)", "LSFT_T(KC_A)", "KC_DOT", "KC_D", "LSFT_T(KC_S)", "LCTL_T(KC_T)", "LALT_T(KC_N)", "LGUI_T(KC_B)",
    "LT(U_BUTTON,KC_J)", "ALGR_T(KC_SLSH)", "KC_COMM", "KC_K", "KC_QUOT", "KC_W", "KC_M", "KC_L", "ALGR_T(KC_P)", "LT(U_BUTTON,KC_V)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_COLEMAK": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_G", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_D", "KC_H", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_K", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_COLEMAKDH": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_G", "KC_M", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_D", "KC_V", "KC_K", "KC_H", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_COLEMAKDHK": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_R)", "LCTL_T(KC_S)", "LSFT_T(KC_T)", "KC_G", "KC_K", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_I)", "LGUI_T(KC_O)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_D", "KC_V", "KC_M", "KC_H", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_DVORAK": [
    "KC_QUOT", "KC_COMM", "KC_DOT", "KC_P", "KC_Y", "KC_F", "KC_G", "KC_C", "KC_R", "KC_L",
    "LGUI_T(KC_A)", "LALT_T(KC_O)", "LCTL_T(KC_E)", "LSFT_T(KC_U)", "KC_I", "KC_D", "LSFT_T(KC_H)", "LCTL_T(KC_T)", "LALT_T(KC_N)", "LGUI_T(KC_S)",
    "LT(U_BUTTON,KC_SLSH)", "ALGR_T(KC_Q)", "KC_J", "KC_K", "KC_X", "KC_B", "KC_M", "KC_W", "ALGR_T(KC_V)", "LT(U_BUTTON,KC_Z)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_HALMAK": [
    "KC_W", "KC_L", "KC_R", "KC_B", "KC_Z", "KC_QUOT", "KC_Q", "KC_U", "KC_D", "KC_J",
    "LGUI_T(KC_S)", "LALT_T(KC_H)", "LCTL_T(KC_N)", "LSFT_T(KC_T)", "KC_COMM", "KC_DOT", "LSFT_T(KC_A)", "LCTL_T(KC_E)", "LALT_T(KC_O)", "LGUI_T(KC_I)",
    "LT(U_BUTTON,KC_F)", "ALGR_T(KC_M)", "KC_V", "KC_C", "KC_SLSH", "KC_G", "KC_P", "KC_X", "ALGR_T(KC_K)", "LT(U_BUTTON,KC_Y)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_WORKMAN": [
    "KC_Q", "KC_D", "KC_R", "KC_W", "KC_B", "KC_J", "KC_F", "KC_U", "KC_P", "KC_QUOT",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_H)", "LSFT_T(KC_T)", "KC_G", "KC_Y", "LSFT_T(KC_N)", "LCTL_T(KC_E)", "LALT_T(KC_O)", "LGUI_T(KC_I)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_M", "KC_C", "KC_V", "KC_K", "KC_L", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_QWERTY": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_QUOT)",
    "LT(U_BUTTON,KC_Z)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "BASE_QWERTZ": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Z", "KC_U", "KC_I", "KC_O", "KC_P",
    "LGUI_T(KC_A)", "LALT_T(KC_S)", "LCTL_T(KC_D)", "LSFT_T(KC_F)", "KC_G", "KC_H", "LSFT_T(KC_J)", "LCTL_T(KC_K)", "LALT_T(KC_L)", "LGUI_T(KC_QUOT)",
    "LT(U_BUTTON,KC_Y)", "ALGR_T(KC_X)", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "ALGR_T(KC_DOT)", "LT(U_BUTTON,KC_SLSH)",
    "LT(U_MEDIA,KC_ESC)", "LT(U_NAV,KC_SPC)", "LT(U_MOUSE,KC_TAB)", "LT(U_SYM,KC_ENT)", "LT(U_NUM,KC_BSPC)", "LT(U_FUN,KC_DEL)",
  ],
  "TAP_AZERTY_FLIP": [
    "KC_A", "KC_Z", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_Q", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_M",
    "KC_W", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_COMM", "KC_DOT", "KC_SLSH", "KC_QUOT",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_BEAKL15_FLIP": [
    "KC_Q", "KC_H", "KC_O", "KC_U", "KC_X", "KC_G", "KC_C", "KC_R", "KC_F", "KC_Z",
    "KC_Y", "KC_I", "KC_E", "KC_A", "KC_DOT", "KC_D", "KC_S", "KC_T", "KC_N", "KC_B",
    "KC_J", "KC_SLSH", "KC_COMM", "KC_K", "KC_QUOT", "KC_W", "KC_M", "KC_L", "KC_P", "KC_V",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_COLEMAK_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_G", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_D", "KC_H", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_K", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_COLEMAKDH_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_G", "KC_M", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_D", "KC_V", "KC_K", "KC_H", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_COLEMAKDHK_FLIP": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_G", "KC_K", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_D", "KC_V", "KC_M", "KC_H", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_DVORAK_FLIP": [
    "KC_QUOT", "KC_COMM", "KC_DOT", "KC_P", "KC_Y", "KC_F", "KC_G", "KC_C", "KC_R", "KC_L",
    "KC_A", "KC_O", "KC_E", "KC_U", "KC_I", "KC_D", "KC_H", "KC_T", "KC_N", "KC_S",
    "KC_SLSH", "KC_Q", "KC_J", "KC_K", "KC_X", "KC_B", "KC_M", "KC_W", "KC_V", "KC_Z",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_HALMAK_FLIP": [
    "KC_W", "KC_L", "KC_R", "KC_B", "KC_Z", "KC_QUOT", "KC_Q", "KC_U", "KC_D", "KC_J",
    "KC_S", "KC_H", "KC_N", "KC_T", "KC_COMM", "KC_DOT", "KC_A", "KC_E", "KC_O", "KC_I",
    "KC_F", "KC_M", "KC_V", "KC_C", "KC_SLSH", "KC_G", "KC_P", "KC_X", "KC_K", "KC_Y",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_WORKMAN_FLIP": [
    "KC_Q", "KC_D", "KC_R", "KC_W", "KC_B", "KC_J", "KC_F", "KC_U", "KC_P", "KC_QUOT",
    "KC_A", "KC_S", "KC_H", "KC_T", "KC_G", "KC_Y", "KC_N", "KC_E", "KC_O", "KC_I",
    "KC_Z", "KC_X", "KC_M", "KC_C", "KC_V", "KC_K", "KC_L", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_QWERTY_FLIP": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_QUOT",
    "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_QWERTZ_FLIP": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Z", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_QUOT",
    "KC_Y", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_DEL", "KC_BSPC", "KC_ENT", "KC_TAB", "KC_SPC", "KC_ESC",
  ],
  "TAP_AZERTY": [
    "KC_A", "KC_Z", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_Q", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_M",
    "KC_W", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_COMM", "KC_DOT", "KC_SLSH", "KC_QUOT",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_BEAKL15": [
    "KC_Q", "KC_H", "KC_O", "KC_U", "KC_X", "KC_G", "KC_C", "KC_R", "KC_F", "KC_Z",
    "KC_Y", "KC_I", "KC_E", "KC_A", "KC_DOT", "KC_D", "KC_S", "KC_T", "KC_N", "KC_B",
    "KC_J", "KC_SLSH", "KC_COMM", "KC_K", "KC_QUOT", "KC_W", "KC_M", "KC_L", "KC_P", "KC_V",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_COLEMAK": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_G", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_D", "KC_H", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_K", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_COLEMAKDH": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_G", "KC_M", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_D", "KC_V", "KC_K", "KC_H", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_COLEMAKDHK": [
    "KC_Q", "KC_W", "KC_F", "KC_P", "KC_B", "KC_J", "KC_L", "KC_U", "KC_Y", "KC_QUOT",
    "KC_A", "KC_R", "KC_S", "KC_T", "KC_G", "KC_K", "KC_N", "KC_E", "KC_I", "KC_O",
    "KC_Z", "KC_X", "KC_C", "KC_D", "KC_V", "KC_M", "KC_H", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_DVORAK": [
    "KC_QUOT", "KC_COMM", "KC_DOT", "KC_P", "KC_Y", "KC_F", "KC_G", "KC_C", "KC_R", "KC_L",
    "KC_A", "KC_O", "KC_E", "KC_U", "KC_I", "KC_D", "KC_H", "KC_T", "KC_N", "KC_S",
    "KC_SLSH", "KC_Q", "KC_J", "KC_K", "KC_X", "KC_B", "KC_M", "KC_W", "KC_V", "KC_Z",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_HALMAK": [
    "KC_W", "KC_L", "KC_R", "KC_B", "KC_Z", "KC_QUOT", "KC_Q", "KC_U", "KC_D", "KC_J",
    "KC_S", "KC_H", "KC_N", "KC_T", "KC_COMM", "KC_DOT", "KC_A", "KC_E", "KC_O", "KC_I",
    "KC_F", "KC_M", "KC_V", "KC_C", "KC_SLSH", "KC_G", "KC_P", "KC_X", "KC_K", "KC_Y",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_WORKMAN": [
    "KC_Q", "KC_D", "KC_R", "KC_W", "KC_B", "KC_J", "KC_F", "KC_U", "KC_P", "KC_QUOT",
    "KC_A", "KC_S", "KC_H", "KC_T", "KC_G", "KC_Y", "KC_N", "KC_E", "KC_O", "KC_I",
    "KC_Z", "KC_X", "KC_M", "KC_C", "KC_V", "KC_K", "KC_L", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_QWERTY": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Y", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_QUOT",
    "KC_Z", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "TAP_QWERTZ": [
    "KC_Q", "KC_W", "KC_E", "KC_R", "KC_T", "KC_Z", "KC_U", "KC_I", "KC_O", "KC_P",
    "KC_A", "KC_S", "KC_D", "KC_F", "KC_G", "KC_H", "KC_J", "KC_K", "KC_L", "KC_QUOT",
    "KC_Y", "KC_X", "KC_C", "KC_V", "KC_B", "KC_N", "KC_M", "KC_COMM", "KC_DOT", "KC_SLSH",
    "KC_ESC", "KC_SPC", "KC_TAB", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "NAV_INVERTEDT_FLIP": [
    "KC_PGUP", "KC_HOME", "KC_UP", "KC_END", "KC_INS", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_PGDN", "KC_LEFT", "KC_DOWN", "KC_RGHT", "CW_TOGG", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_NA", "TD(U_TD_U_NAV)", "TD(U_TD_U_NUM)", "KC_ALGR", "U_NA",
    "KC_DEL", "KC_BSPC", "KC_ENT", "U_NA", "U_NA", "U_NA",
  ],
  "NAV_FLIP": [
    "KC_HOME", "KC_PGDN", "KC_PGUP", "KC_END", "KC_INS", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_LEFT", "KC_DOWN", "KC_UP", "KC_RGHT", "CW_TOGG", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_NA", "TD(U_TD_U_NAV)", "TD(U_TD_U_NUM)", "KC_ALGR", "U_NA",
    "KC_DEL", "KC_BSPC", "KC_ENT", "U_NA", "U_NA", "U_NA",
  ],
  "NAV_INVERTEDT": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "KC_INS", "KC_HOME", "KC_UP", "KC_END", "KC_PGUP",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "CW_TOGG", "KC_LEFT", "KC_DOWN", "KC_RGHT", "KC_PGDN",
    "U_NA", "KC_ALGR", "TD(U_TD_U_NUM)", "TD(U_TD_U_NAV)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "U_NA", "U_NA", "U_NA", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "NAV_VI": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_LEFT", "KC_DOWN", "KC_UP", "KC_RGHT", "CW_TOGG",
    "U_NA", "KC_ALGR", "TD(U_TD_U_NUM)", "TD(U_TD_U_NAV)", "U_NA", "KC_HOME", "KC_PGDN", "KC_PGUP", "KC_END", "KC_INS",
    "U_NA", "U_NA", "U_NA", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "NAV": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "CW_TOGG", "KC_LEFT", "KC_DOWN", "KC_UP", "KC_RGHT",
    "U_NA", "KC_ALGR", "TD(U_TD_U_NUM)", "TD(U_TD_U_NAV)", "U_NA", "KC_INS", "KC_HOME", "KC_PGDN", "KC_PGUP", "KC_END",
    "U_NA", "U_NA", "U_NA", "KC_ENT", "KC_BSPC", "KC_DEL",
  ],
  "MOUSE_INVERTEDT_FLIP": [
    "KC_WH_U", "KC_WH_L", "KC_MS_U", "KC_WH_R", "U_NU", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_WH_D", "KC_MS_L", "KC_MS_D", "KC_MS_R", "U_NU", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_NA", "TD(U_TD_U_MOUSE)", "TD(U_TD_U_SYM)", "KC_ALGR", "U_NA",
    "KC_BTN3", "KC_BTN1", "KC_BTN2", "U_NA", "U_NA", "U_NA",
  ],
  "MOUSE_FLIP": [
    "KC_WH_L", "KC_WH_D", "KC_WH_U", "KC_WH_R", "U_NU", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_MS_L", "KC_MS_D", "KC_MS_U", "KC_MS_R", "U_NU", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_NA", "TD(U_TD_U_MOUSE)", "TD(U_TD_U_SYM)", "KC_ALGR", "U_NA",
    "KC_BTN3", "KC_BTN1", "KC_BTN2", "U_NA", "U_NA", "U_NA",
  ],
  "MOUSE_INVERTEDT": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "U_NU", "KC_WH_L", "KC_MS_U", "KC_WH_R", "KC_WH_U",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "U_NU", "KC_MS_L", "KC_MS_D", "KC_MS_R", "KC_WH_D",
    "U_NA", "KC_ALGR", "TD(U_TD_U_SYM)", "TD(U_TD_U_MOUSE)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "U_NA", "U_NA", "U_NA", "KC_BTN2", "KC_BTN1", "KC_BTN3",
  ],
  "MOUSE_VI": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_MS_L", "KC_MS_D", "KC_MS_U", "KC_MS_R", "U_NU",
    "U_NA", "KC_ALGR", "TD(U_TD_U_SYM)", "TD(U_TD_U_MOUSE)", "U_NA", "KC_WH_L", "KC_WH_D", "KC_WH_U", "KC_WH_R", "U_NU",
    "U_NA", "U_NA", "U_NA", "KC_BTN2", "KC_BTN1", "KC_BTN3",
  ],
  "MOUSE": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "U_NU", "KC_MS_L", "KC_MS_D", "KC_MS_U", "KC_MS_R",
    "U_NA", "KC_ALGR", "TD(U_TD_U_SYM)", "TD(U_TD_U_MOUSE)", "U_NA", "U_NU", "KC_WH_L", "KC_WH_D", "KC_WH_U", "KC_WH_R",
    "U_NA", "U_NA", "U_NA", "KC_BTN2", "KC_BTN1", "KC_BTN3",
  ],
  "MEDIA_INVERTEDT_FLIP": [
    "RGB_HUI", "RGB_SAI", "KC_VOLU", "RGB_VAI", "RGB_TOG", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "RGB_MOD", "KC_MPRV", "KC_VOLD", "KC_MNXT", "U_NU", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_NU", "U_NU", "U_NU", "U_NU", "OU_AUTO", "U_NA", "TD(U_TD_U_MEDIA)", "TD(U_TD_U_FUN)", "KC_ALGR", "U_NA",
    "KC_MUTE", "KC_MPLY", "KC_MSTP", "U_NA", "U_NA", "U_NA",
  ],
  "MEDIA_FLIP": [
    "RGB_MOD", "RGB_HUI", "RGB_SAI", "RGB_VAI", "RGB_TOG", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_MPRV", "KC_VOLD", "KC_VOLU", "KC_MNXT", "U_NU", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_NU", "U_NU", "U_NU", "U_NU", "OU_AUTO", "U_NA", "TD(U_TD_U_MEDIA)", "TD(U_TD_U_FUN)", "KC_ALGR", "U_NA",
    "KC_MUTE", "KC_MPLY", "KC_MSTP", "U_NA", "U_NA", "U_NA",
  ],
  "MEDIA_INVERTEDT": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "RGB_TOG", "RGB_MOD", "KC_VOLU", "RGB_HUI", "RGB_SAI",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "U_NU", "KC_MPRV", "KC_VOLD", "KC_MNXT", "RGB_VAI",
    "U_NA", "KC_ALGR", "TD(U_TD_U_FUN)", "TD(U_TD_U_MEDIA)", "U_NA", "OU_AUTO", "U_NU", "U_NU", "U_NU", "U_NU",
    "U_NA", "U_NA", "U_NA", "KC_MSTP", "KC_MPLY", "KC_MUTE",
  ],
  "MEDIA_VI": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "RGB_MOD", "RGB_HUI", "RGB_SAI", "RGB_VAI", "RGB_TOG",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_MPRV", "KC_VOLD", "KC_VOLU", "KC_MNXT", "U_NU",
    "U_NA", "KC_ALGR", "TD(U_TD_U_FUN)", "TD(U_TD_U_MEDIA)", "U_NA", "U_NU", "U_NU", "U_NU", "U_NU", "OU_AUTO",
    "U_NA", "U_NA", "U_NA", "KC_MSTP", "KC_MPLY", "KC_MUTE",
  ],
  "MEDIA": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "RGB_TOG", "RGB_MOD", "RGB_HUI", "RGB_SAI", "RGB_VAI",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "U_NU", "KC_MPRV", "KC_VOLD", "KC_VOLU", "KC_MNXT",
    "U_NA", "KC_ALGR", "TD(U_TD_U_FUN)", "TD(U_TD_U_MEDIA)", "U_NA", "OU_AUTO", "U_NU", "U_NU", "U_NU", "U_NU",
    "U_NA", "U_NA", "U_NA", "KC_MSTP", "KC_MPLY", "KC_MUTE",
  ],
  "NUM_FLIP": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "KC_LBRC", "KC_7", "KC_8", "KC_9", "KC_RBRC",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_EQL", "KC_4", "KC_5", "KC_6", "KC_SCLN",
    "U_NA", "KC_ALGR", "TD(U_TD_U_NAV)", "TD(U_TD_U_NUM)", "U_NA", "KC_BSLS", "KC_1", "KC_2", "KC_3", "KC_GRV",
    "U_NA", "U_NA", "U_NA", "KC_MINS", "KC_0", "KC_DOT",
  ],
  "NUM": [
    "KC_LBRC", "KC_7", "KC_8", "KC_9", "KC_RBRC", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_SCLN", "KC_4", "KC_5", "KC_6", "KC_EQL", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "KC_GRV", "KC_1", "KC_2", "KC_3", "KC_BSLS", "U_NA", "TD(U_TD_U_NUM)", "TD(U_TD_U_NAV)", "KC_ALGR", "U_NA",
    "KC_DOT", "KC_0", "KC_MINS", "U_NA", "U_NA", "U_NA",
  ],
  "SYM_FLIP": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "KC_LCBR", "KC_AMPR", "KC_ASTR", "KC_LPRN", "KC_RCBR",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_PLUS", "KC_DLR", "KC_PERC", "KC_CIRC", "KC_COLN",
    "U_NA", "KC_ALGR", "TD(U_TD_U_MOUSE)", "TD(U_TD_U_SYM)", "U_NA", "KC_PIPE", "KC_EXLM", "KC_AT", "KC_HASH", "KC_TILD",
    "U_NA", "U_NA", "U_NA", "KC_UNDS", "KC_LPRN", "KC_RPRN",
  ],
  "SYM": [
    "KC_LCBR", "KC_AMPR", "KC_ASTR", "KC_LPRN", "KC_RCBR", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_COLN", "KC_DLR", "KC_PERC", "KC_CIRC", "KC_PLUS", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "KC_TILD", "KC_EXLM", "KC_AT", "KC_HASH", "KC_PIPE", "U_NA", "TD(U_TD_U_SYM)", "TD(U_TD_U_MOUSE)", "KC_ALGR", "U_NA",
    "KC_LPRN", "KC_RPRN", "KC_UNDS", "U_NA", "U_NA", "U_NA",
  ],
  "FUN_FLIP": [
    "TD(U_TD_BOOT)", "TD(U_TD_U_TAP)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_BASE)", "U_NA", "KC_PSCR", "KC_F7", "KC_F8", "KC_F9", "KC_F12",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NA", "KC_SCRL", "KC_F4", "KC_F5", "KC_F6", "KC_F11",
    "U_NA", "KC_ALGR", "TD(U_TD_U_MEDIA)", "TD(U_TD_U_FUN)", "U_NA", "KC_PAUS", "KC_F1", "KC_F2", "KC_F3", "KC_F10",
    "U_NA", "U_NA", "U_NA", "KC_TAB", "KC_SPC", "KC_APP",
  ],
  "FUN": [
    "KC_F12", "KC_F7", "KC_F8", "KC_F9", "KC_PSCR", "U_NA", "TD(U_TD_U_BASE)", "TD(U_TD_U_EXTRA)", "TD(U_TD_U_TAP)", "TD(U_TD_BOOT)",
    "KC_F11", "KC_F4", "KC_F5", "KC_F6", "KC_SCRL", "U_NA", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "KC_F10", "KC_F1", "KC_F2", "KC_F3", "KC_PAUS", "U_NA", "TD(U_TD_U_FUN)", "TD(U_TD_U_MEDIA)", "KC_ALGR", "U_NA",
    "KC_APP", "KC_SPC", "KC_TAB", "U_NA", "U_NA", "U_NA",
  ],
  "BUTTON": [
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_LGUI", "KC_LALT", "KC_LCTL", "KC_LSFT", "U_NU", "U_NU", "KC_LSFT", "KC_LCTL", "KC_LALT", "KC_LGUI",
    "U_UND", "U_CUT", "U_CPY", "U_PST", "U_RDO", "U_RDO", "U_PST", "U_CPY", "U_CUT", "U_UND",
    "KC_BTN3", "KC_BTN1", "KC_BTN2", "KC_BTN2", "KC_BTN1", "KC_BTN3",
  ],
};
